/**
 * Room ID format: alphanumeric (a-z, 0-9), length 4–32.
 * Matches IDs generated by uuidv4().slice(0, 8) and allows longer codes.
 */
const ROOM_ID_REGEX = /^[a-z0-9]{4,32}$/;

export function isValidRoomId(roomId: string): boolean {
  if (!roomId || typeof roomId !== "string") return false;
  const normalized = roomId.trim().toLowerCase();
  return ROOM_ID_REGEX.test(normalized);
}
